# Generated by Django 2.1 on 2020-08-22 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 4, 46, 17, 632317, tzinfo=utc)),
        ),
    ]
